Streamline GitHub actions
bedwardly-down/dragonruby-cext-libsocket pull request #13
Opened 2023-04-11 11:02 UTC by kfischer-okarin

Takes care of #10 

- Extracted DR download into a script
- Extracted build into a script
- Added a small helper script that determines the DR platform automatically so you don't need to specify the platform manually anymore
- Now there's only 1 job definition which runs via a matrix of parameters

I did **not** summarize the upload artifact steps.... it would be possible... but I thought the visual overhead of trying to add more parameters/steps/variable settings just to unify that one step... was too much... so I kept it like this ;)

2023-04-11 20:34 UTC, bedwardly-down requested changes
See comments about the Windows side of things. Unless you have some ideas to throw in or some concerns with my own commit that was added, this currently looks good to me and is ready to merge.

2023-04-11 23:17 UTC, kfischer-okarin commented on scripts/build.sh
> +fi
I'm not sure I can agree with this change..... 

At first glance, It seems convenien...
But I think when working on this library locally / or even just wanting to compile the extension on your own machine (for whatever reason) setup will look quite different from this... on/off build on an empty CI machine

I agree that you need to be able to specify the location of your DR headers somehow (need to think about that a bit more) but downloading the CI version of Dragonruby doesn't seem like the right approach for local development/building

2023-04-11 23:22 UTC, kfischer-okarin commented
> If a developer wants to use the build script through something like git bash

Just to confirm...
I'm not familiar with common dev setups for windows... I suppose it's reasonable to assume at least that they have some kind of `bash` right? EIther Git Bash or some kind of Msys/Mingw kind of environment?

2023-04-11 23:25 UTC, bedwardly-down commented on scripts/build.sh
> +fi
I agree. I think having the scripts folder be exposed like it is in the original PR is a bad idea and that all building needs to directly be handled by the contributor and developer.

2023-04-11 23:44 UTC, bedwardly-down commented on scripts/build.sh
> +fi
That I agree with.

2023-04-12 00:06 UTC, bedwardly-down reviewed
I have one concern with this: how many fresh developers trying out DR for the first time and taking the plunge into the licensed portion of it will understand what SYSROOT pertains to? I’d change to MINGW_DIR or something more descriptive for what the variable actually is for to the non tech minded user.

2023-04-12 00:43 UTC, bedwardly-down approved these changes
Thanks for not modifying the .gitignore file. That change was primarily for the sanity and safety of the repo. And even if someone does push unwanted files, I can immediately deny the PR altogether

2023-04-12 00:43 UTC, bedwardly-down commented on scripts/build.sh
> +fi
I won’t be home for a few hours. If you push a commit with the trouble section removed and address my one last concern, I think this can be safely merged into dev. It’s not going to conflict with anything I’m working on and definitely should be scalable and maintainable.

2023-04-12 00:46 UTC, merged